config/routes.rb
Rails.application.routes.draw do
  root 'groups#index'
  devise_for :users

  resources :groups do
    post '/join', as: :member, to: 'groups#join'
    delete '/remove', to: 'groups#remove'
    resources :posts do
      resources :comments, shallow: true do 
        resources :replies
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post

    has_many :replies, dependent: :destroy

    validates :content, presence: true
end
  

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  validates_uniqueness_of :name


  belongs_to :user

  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups
  has_many :posts, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :group

  has_many :comments, dependent: :destroy

  validates :title, :content, presence: true
end

app/models/reply.rb
class Reply < ApplicationRecord
    belongs_to :user
    belongs_to :comment

    validates :content, presence: true
end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_groups, dependent: :destroy
  has_many :groups, through: :user_groups
  has_many :posts
  has_many :comments, dependent: :destroy
  has_many :owned_groups, class_name: 'Group', dependent: :destroy
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end


  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_group, :set_post, :set_reply
  
    def create
      @comment = @post.comments.new(comment_params.merge(user: current_user))
      if @comment.save
        render turbo_stream: turbo_stream.append(
          'post_comments',
          CommentComponent.new(comment: @comment, current_user: current_user).render_in(view_context)
        )
      else
        render turbo_stream: turbo_stream.replace(
         'comment_form',
          partial: 'form',
          locals: {
            comment: @comment
          }
      ), status: :unprocessable_entity
      end
    end

    private

    def comment_params
      params.require(:comment).permit(:content)
    end

    def set_post
      @post = Post.find(params[:post_id])
    end

    def set_group
      @group = Group.find(params[:group_id])
    end 

    def set_reply
      @reply = Reply.new
    end
end
  

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:edit, :show, :update]

  def index
    @groups = case params[:search]
              when 'owned'
                current_user.owned_groups
              when 'member'
                current_user.groups
              else
                Group.all
              end
    @groups = @groups.includes(:users, :posts)
  end

  def new
    @group = Group.new
  end

  def show
    @posts = @group.posts
    @users = @group.users
    @post = Post.new
  end

  def edit; end

  def update
    @group.update(group_params)
    redirect_to group_path(@group), status: :see_other
  end

  def create
    @group = Group.new(group_params.merge(user: current_user))
    if @group.save
      render turbo_stream: turbo_stream.append(
        'groups',
        partial: 'group',
        locals: {
          group: @group
        }
      )
    else
      render turbo_stream: turbo_stream.replace(
       'group_form',
        partial: 'form',
        locals: {
          group: @group
        }
    ), status: :unprocessable_entity
    end
  end

  def join
    @group = Group.find(params[:group_id])
    @group.users << current_user
    render turbo_stream: turbo_stream.replace("join_member_#{@group.id}", '')
  end

  def remove
    @group = Group.find(params[:group_id])
    authorize @group
    user_group = @group.user_groups.find_by(user_id: params[:user_id])
    user_group&.destroy
    render turbo_stream: turbo_stream.replace("remove_member_#{params[:user_id]}", '')
  end

  private

  def group_params
    params.require(:group).permit(:name)
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, except: [ :index, :create ]
  before_action :set_group


  def show
    @post = Post.includes(comments: :replies).find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
    @reply = Reply.new
  end

  def create
    @post = @group.posts.new(post_params.merge(user: current_user))
    authorize @group
    if @post.save
      render turbo_stream: turbo_stream.append(
        'posts',
        partial: 'post',
        locals: {
          post: @post
        }
      )
    else
      render turbo_stream: turbo_stream.replace(
       'post_form',
        partial: 'form',
        locals: {
          post: @post
        }
    ), status: :unprocessable_entity
    end
  end

  def update
    authorize @post
    @post.update(post_params)
    redirect_to group_post_path(@group, @post),  notice: "Post was successfully updated."
  end 

  def destroy
    authorize @post
    @post.destroy
    redirect_to group_path(@group), status: :see_other, notice: "Post was successfully destroyed."
  end


  def post_params
    params.require(:post).permit(:title, :content)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
    before_action :set_comment
  
    def create
      @reply = @comment.replies.new(reply_params.merge(user: current_user))
      if @reply.save
        render turbo_stream: turbo_stream.append(
          "comment_replies_#{@comment.id}",
          ReplyComponent.new(reply: @reply, current_user: current_user).render_in(view_context)
        )
      else
        render turbo_stream: turbo_stream.replace(
         "reply_form_#{@comment.id}",
          partial: 'form',
          locals: {
            reply: @reply,
            comment: @comment
          }
      ), status: :unprocessable_entity
      end
    end

    private

    def reply_params
      params.require(:reply).permit(:content)
    end

    def set_comment
      @comment = Comment.find(params[:comment_id])
    end 
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def creator_name post
    post.user == current_user ? "You" : post.user.name
  end
end

app/views/comments/_form.html.erb
<div class="flex flex-col justify-center">
    <div class="w-full bg-white rounded-lg md:mt-0 sm:max-w-md xl:p-0">
      <div>
        <%= form_with(model: [@group, @post, @comment] , id: "comment_form", data: {controller: 'reset-form', action: "turbo:submit-end->reset-form#reset" }, class: "space-y-4 md:space-y-6") do |form| %>
          <div class="px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
            <% if @comment.errors.any? %>
              <div class="p-4 border border-red-600", data-extended-modal-target="errors">
                <ul>
                  <% @comment.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
              <div class="form-group">
              <%= form.label :content, class: "block mb-2 text-sm font-medium text-gray-900" %>
              <%= form.text_area :content, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:border-gray-600 dark:placeholder-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
            </div>
            <div class="rounded-b mt-4 px-2 pt-2 sm:grid sm:grid-cols-2 sm:gap-3 sm:grid-flow-row-dense">
              <%= form.button class: "w-full text-blue bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:bg-gray-700 dark:text-white" %>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: @group, id: "group_form", data: { extended_modal_target: 'form' }) do |form| %>
  
  <div class="px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
    <% if @group.errors.any? %>
      <div class="p-4 border border-red-600", data-extended-modal-target="errors">
        <ul>
          <% @group.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

  </div>
  <div class="rounded-b mt-6 px-4 sm:grid sm:grid-cols-2 sm:gap-3 sm:grid-flow-row-dense">
    <%= form.button class: "w-full sm:col-start-2 bg-blue-600 px-4 py-2 mb-4 text-white rounded-sm hover:bg-blue-700" %>
    <button data-action="click->extended-modal#close" class="mt-3 w-full sm:mt-0 sm:col-start-1 mb-4 bg-gray-100 hover:bg-gray-200 rounded-sm px-4 py-2">
      Cancel
    </button>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div class="text-gray-700 w-3/6 pb-4 pl-4">
  <div class="flex <%= policy(group).owner? ? '' : 'justify-between' %>">
    <%= link_to group.name, group_path(group), class: "ftext-2xl font-normal leading-normal mt-0 mb-2 text-pink-800"%>
    <% if policy(group).owner?  %>
        <span class="pl-2 text-gray-500">Created by me</span>
    <% elsif !policy(group).group_member? %>
        <%= turbo_frame_tag "join_member_#{group.id}" do %>
          <%= link_to 'Join', group_member_path(group), data: { "turbo_method": "post" }, class: "ftext-2xl font-normal leading-none mt-0 mb-2 py-1 px-4 text-black border border-black-700 rounded"%>
        <% end %>
    <% end %>
  </div>
  <div>
    <%= group.users.size %> members <%= group.posts.length %> posts
  </div>
</div>

app/views/groups/_member.html.erb
<div class="pb-2">
   <%= turbo_frame_tag "remove_member_#{user.id}" do %>
        <%= user.name %> 
        <% if policy(@group).remove? %>
            <%= link_to group_remove_path(@group, user_id: user.id), data: { turbo_method: "delete" } do %>
            <i class="fa-solid fa-xmark"></i>
            <% end %>
        <% end %>
    <% end %>
</div>

app/views/groups/_modal.html.erb
<div data-extended-modal-target="container" class="hidden animated fadeIn fixed inset-0 overflow-y-auto flex items-center justify-center" data-action="turbo:submit-end->extended-modal#handleSuccess" style="z-index: 9999;">
  <div class="max-w-lg max-h-screen w-full relative">
    <div class="m-1 bg-white rounded shadow">
      <div class="px-4 py-5 border-b border-gray-200 sm:px-6">
        <h3 class="text-lg leading-6 font-medium text-gray-900">
          Group
        </h3>
      </div>
      <form id="group_form"></form>
    </div>
  </div>
</div>

app/views/groups/edit.html.erb
<%= turbo_frame_tag "group_modal" do %>
  <turbo-stream target="group_form" action="replace">
  <template>
      <%= render partial: "form", locals: { group: @group } %>
  </template>
  </turbo-stream>
<% end %>

app/views/groups/index.html.erb
<%= turbo_frame_tag 'group_modal' %>

<%= turbo_frame_tag "groups" do %>
    <%= turbo_frame_tag "posts" do %>
        <%= turbo_frame_tag "comments" do %>
        <div>
        <p>
            <h3 class="font-medium leading-tight text-3xl mt-0 mb-2 text-black-600 pl-4">Groups</h3>
        </p>
        <div>
            <div class="flex justify-between p-4">
                <div>
                    <ul class="hidden text-sm font-medium text-center text-gray-500 rounded-lg divide-x divide-gray-200 shadow sm:flex dark:divide-gray-700 dark:text-gray-400">
                        <li class="max-w-max">
                        <%= link_to 'All Groups', groups_path, class: "max-w-max inline-block p-4 text-gray-900 bg-gray-100 rounded-l-lg focus:ring-4 focus:ring-blue-300 active focus:outline-none dark:bg-gray-700 dark:text-white"  %>
                        </li>
                        <li class="max-w-max">
                        <%= link_to 'Created by me', groups_path(search: 'owned'), class: "max-w-max inline-block p-4  bg-white hover:text-gray-700 hover:bg-gray-50 focus:ring-4 focus:ring-blue-300 focus:outline-none dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700" %>
                        </li>
                        <li class="max-w-max">
                        <%= link_to 'Where i am member', groups_path(search: 'member'), class: "max-w-max inline-block p-4 bg-white hover:text-gray-700 hover:bg-gray-50 focus:ring-4 focus:ring-blue-300 focus:outline-none dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700" %>
                        </li>
                    </ul>
                </div>
                <% if policy(Group).new? %>
                <div class="flex justify-between items-baseline" data-controller="extended-modal" data-extended-modal-prevent-default-action-opening="false">
                    <%= render 'modal' %>
                    <%= link_to new_group_path, class: "self-center", data: { action: "click->extended-modal#open", 'turbo-frame': 'group_modal' } do %>
                        <span><i class="fa-solid fa-plus"></i> Create New Group </span>
                    <% end %>
                </div>
                <% end %>
            </div>
            <% @groups.each do |group| %>
            <%= render "group", group: group %>
            <% end %>
        </div>
        <% end %>
    <% end %>
<%end %>

app/views/groups/new.html.erb
<%= turbo_frame_tag "group_modal" do %>
  <turbo-stream target="group_form" action="replace">
  <template>
      <%= render partial: "form", locals: { group: @group } %>
  </template>
  </turbo-stream>
<% end %>

app/views/groups/show.html.erb
<%= turbo_frame_tag "groups" do %>
 <%= turbo_frame_tag "posts",  class: "flex flex-col items-baseline space-y-6 p-4 shadow-lg rounded" do %>
   <%= turbo_frame_tag "comments" do %>
 <div class='flex flex-row justify-between w-full'>
    <div class="w-4/6 pl-4">
        My Group
        <% if policy(@group).create? %>
          <div class="max-h-screen w-full">
            <%= render "posts/form"%>
          </div>
        <% end %>
        <h3 class="font-medium leading-tight text-3xl mt-0 mb-2 text-blue-600">All Posts</h3>
        <% @posts.each do |post| %>
          <div class='pb-1 W-4/6'>
            <div class='h-[120px]'>
              <%= render "posts/post", post: post %>
            </div>
            <%= link_to 'View Post', group_post_path(@group, post), class: "ftext-2xl font-normal leading-none mt-0 mb-2 py-1 px-4 text-black border border-black-700 rounded" %>
          </div>
        <% end %>
    </div>
    <div>
      Members
      <% @group.users.each do |user| %>
         <%= render 'member', user: user %>
      <% end %>
    </div>
  </div>
  <%end%>
 <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simplero</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body class='min-h-full bg-white'>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="flex flex-col justify-center">
    <div class="w-full bg-white rounded-lg md:mt-0 sm:max-w-md xl:p-0">
      <div class="p-2 sm:p-8">
        <%= form_with(model: [@group, @post], id: "post_form", data: {controller: 'reset-form', action: "turbo:submit-end->reset-form#reset" }, class: "space-y-4 md:space-y-6") do |form| %>
          
          <div>
            <% if @post.errors.any? %>
              <div class="p-4 border border-red-600", data-extended-modal-target="errors">
                <ul>
                  <% @post.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="form-group pb-2">
              <%= form.label :title, class: "block mb-2 text-sm font-medium text-gray-900" %>
              <%= form.text_field :title, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:border-gray-600 dark:placeholder-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
            </div>

              <div class="form-group">
              <%= form.label :content, class: "block mb-2 text-sm font-medium text-gray-900" %>
              <%= form.text_area :content, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:border-gray-600 dark:placeholder-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
            </div>

            <div class="rounded-b mt-6 px-4 sm:grid sm:grid-cols-2 sm:gap-3 sm:grid-flow-row-dense">
            <%= form.button class: "w-full text-blue bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:bg-gray-700 dark:text-white" %>
            </div>

          </div>
        <% end %>
     </div>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="w-full">
  <div class="text-gray-700 w-full pb-1">
    <%= link_to post.title, group_post_path(@group.id, post.id), class: "ftext-2xl font-normal leading-normal mt-0 mb-2 text-pink-800"%>
  </div>
  <div class="font-light leading-normal pb-2">
    <div> 
      <%= post.content %>
    </div>
     <% if policy(post).edit? %>
      <span class="text-lg font-bold"> <%= link_to 'Edit', edit_group_post_path(@group, post)%></span> | 
      <span class="text-lg font-bold "> <%= link_to "Delete", group_post_path(@group, post), data: { "turbo_method": :delete } %></span>
    <% end %> |<span class="text-lg font-bold">Created by <%= creator_name(post)%></span>
  </div>
</div>

app/views/posts/edit.html.erb
<%= turbo_frame_tag "posts" do %>
  <%= turbo_frame_tag "comments" do %>
    <%= render 'form' %>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<%= turbo_frame_tag "posts" do %>
<%= turbo_frame_tag "comments" do %>
  <%= render "post",  post: @post %>
  <%= turbo_frame_tag "post_comments" do %>
    <div class='pt-6'>
        Comments
        <%= render(CommentComponent.with_collection(@comments, current_user: current_user)) %>
    </div>
  <% end %>
  <h2>Add New Comment</h2>
  <%= render "comments/form" %>
 <% end %>
<% end %>

app/views/replies/_form.html.erb
<div class="flex flex-col justify-center">
    <div class="w-full bg-white rounded-lg md:mt-0 sm:max-w-md xl:p-0">
      <div>
        <%= form_with(model: @reply, url: comment_replies_url(comment) , id: "reply_form_#{comment.id}", data: {controller: 'reset-form', action: "turbo:submit-end->reset-form#reset" }, class: "space-y-4 md:space-y-6") do |form| %>
          <div class="px-4 pb-4 sm:p-6 sm:pb-4">
            <% if @reply.errors.any? %>
              <div class="px-4 border border-red-600", data-extended-modal-target="errors">
                <ul>
                  <% @reply.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
              <div class="form-group">
              <%= form.label :content, class: "block mb-2 text-sm font-medium text-gray-900" %>
              <%= form.text_area :content, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:border-gray-600 dark:placeholder-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
            </div>
            <div class="rounded-b mt-4 px-2 pt-2 sm:grid sm:grid-cols-2 sm:gap-3 sm:grid-flow-row-dense">
              <%= form.button class: "w-full text-blue bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:bg-gray-700 dark:text-white" %>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="relative flex flex-wrap items-center justify-between px-2 py-3 bg-red-500 mb-3">
  <div class="container px-4 mx-auto flex flex-wrap items-center justify-between">
    <div class="w-full relative flex justify-between lg:w-auto  px-4 lg:static lg:block lg:justify-start">
      <a class="text-sm font-bold leading-relaxed inline-block mr-4 py-2 whitespace-nowrap uppercase text-white" href="#pablo">
        Simplero
      </a>
      <button class="cursor-pointer text-xl leading-none px-3 py-1 border border-solid border-transparent rounded bg-transparent block lg:hidden outline-none focus:outline-none" type="button">
        <span class="block relative w-6 h-px rounded-sm bg-white"></span>
        <span class="block relative w-6 h-px rounded-sm bg-white mt-1"></span>
        <span class="block relative w-6 h-px rounded-sm bg-white mt-1"></span>
      </button>
    </div>
    <div class="lg:flex flex-grow items-center" id="example-navbar-warning">
      <ul class="flex flex-col lg:flex-row list-none ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="px-3 py-2 flex items-center text-xs uppercase font-bold leading-snug text-white hover:opacity-75" href="<%= groups_path %>">
              Groups
            </a>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: 'px-3 py-2 flex items-center text-xs uppercase font-bold leading-snug text-white hover:opacity-75' %>
          </li>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, class: "px-3 py-2 flex items-center text-xs uppercase font-bold leading-snug text-white hover:opacity-75" %> |
          <%= link_to "Login", new_user_session_path, class: "px-3 py-2 flex items-center text-xs uppercase font-bold leading-snug text-white hover:opacity-75" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>